# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291d5900ede832ae96c35f131857cf82e182a317dc7d4de0a5d769d2e6d6c7069d6d345587d8304fa5d9e1814856f73f69bcaa922c9ad019f330011a29b45090

test:
  secret_key_base: c2bd9c6ec5a64fbcb9b0a585b540aab1a03d554021ca33f0f15f2ea446f08dbd95b65bfe65c2436bf6875d13184b0e2dcd8699f95a9e1ee230498de9c8232f64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
