

@al = State.create!(name: "Alabama", abbreviation: "AL", population: 4802982, num_reps: 7)
@ak = State.create(name: "Alaska", abbreviation: 'AK', population: 721523, num_reps: 1)
@az = State.create(name: "Arizona", abbreviation: 'AZ', population: 6412700, num_reps: 9)
@ar = State.create(name: "Arkansas", abbreviation: 'AR', population: 2926229, num_reps: 4)
@ca = State.create(name: "California", abbreviation: 'CA', population: 37341989, num_reps: 53)
@co = State.create(name: "Colorado", abbreviation: 'CO', population: 5044930, num_reps: 7)
@ct = State.create(name: "Connecticut", abbreviation: 'CT', population: 3581628, num_reps: 5)
@de = State.create(name: "Delaware", abbreviation: 'DE', population: 900877, num_reps: 1)
@fl = State.create(name: "Florida", abbreviation: 'FL', population: 18900773, num_reps: 27)
@ga = State.create(name: "Georgia", abbreviation: 'GA', population: 9727566, num_reps: 14)
@hi = State.create(name: "Hawaii", abbreviation: 'HI', population: 1366862, num_reps: 2)
@id = State.create(name: "Idaho", abbreviation: 'ID', population: 1573499, num_reps: 2)
@il = State.create(name: "Illinois", abbreviation: 'IL', population: 12864380, num_reps: 18)
@in = State.create(name: "Indiana", abbreviation: 'IN', population: 6501582, num_reps: 9)
@ia = State.create(name: "Iowa", abbreviation: 'IA', population: 3053787, num_reps: 4)
@ks = State.create(name: "Kansas", abbreviation: 'KS', population: 2863813, num_reps: 4)
@ky = State.create(name: "Kentucky", abbreviation: 'KY', population: 4350606, num_reps: 6)
@la = State.create(name: "Louisiana", abbreviation: 'LA', population: 4553962, num_reps: 6)
@me = State.create(name: "Maine", abbreviation: 'ME', population: 1333074, num_reps: 2)
@md = State.create(name: "Maryland", abbreviation: 'MD', population: 5789929, num_reps: 8)
@ma = State.create(name: "Massachusetts", abbreviation: 'MA', population: 6559644, num_reps: 9)
@mi = State.create(name: "Michigan", abbreviation: 'MI', population: 9911626, num_reps: 14)
@mn = State.create(name: "Minnesota", abbreviation: 'MN', population: 5314879, num_reps: 8)
@ms = State.create(name: "Mississippi", abbreviation: 'MS', population: 2978240, num_reps: 4)
@mo = State.create(name: "Missouri", abbreviation: 'MO', population: 6011478, num_reps: 8)
@mt = State.create(name: "Montana", abbreviation: 'MT', population: 994416, num_reps: 1)
@ne = State.create(name: "Nebraska", abbreviation: 'NE', population: 1831825, num_reps: 3)
@nv = State.create(name: "Nevada", abbreviation: 'NV', population: 2709432, num_reps: 4)
@nh = State.create(name: "New Hampshire", abbreviation: 'NH', population: 1321445, num_reps: 2)
@nj = State.create(name: "New Jersey", abbreviation: 'NJ', population: 8807501, num_reps: 12)
@nm = State.create(name: "New Mexico", abbreviation: 'NM', population: 2067273, num_reps: 3)
@ny = State.create(name: "New York", abbreviation: 'NY', population: 19421055, num_reps: 27)
@nc = State.create(name: "North Carolina", abbreviation: 'NC', population: 9565781, num_reps: 13)
@nd = State.create(name: "North Dakota", abbreviation: 'ND', population: 675905, num_reps: 1)
@oh = State.create(name: "Ohio", abbreviation: 'OH', population: 11568495, num_reps: 16)
@ok = State.create(name: "Oklahoma", abbreviation: 'OK', population: 3764882, num_reps: 5)
@or = State.create(name: "Oregon", abbreviation: 'OR', population: 3848606, num_reps: 5)
@pa = State.create(name: "Pennsylvania", abbreviation: 'PA', population: 12734905, num_reps: 18)
@ri = State.create(name: "Rhode Island", abbreviation: 'RI', population: 1055247, num_reps: 2)
@sc = State.create(name: "South Carolina", abbreviation: 'SC', population: 4645975, num_reps: 7)
@sd = State.create(name: "South Dakota", abbreviation: 'SD', population: 819761, num_reps: 1)
@tn = State.create(name: "Tennessee", abbreviation: 'TN', population: 6375431, num_reps: 9)
@tx = State.create(name: "Texas", abbreviation: 'TX', population: 25268418, num_reps: 36)
@ut = State.create(name: "Utah", abbreviation: 'UT', population: 2770765, num_reps: 4)
@vt = State.create(name: "Vermont", abbreviation: 'VT', population: 630337, num_reps: 1)
@va = State.create(name: "Virginia", abbreviation: 'VA', population: 8037736, num_reps: 11)
@wa = State.create(name: "Washington", abbreviation: 'WA', population: 6753369, num_reps: 10)
@wv = State.create(name: "West Virginia", abbreviation: 'WV', population: 1859815, num_reps: 3)
@wi = State.create(name: "Wisconsin", abbreviation: 'WI', population: 5698230, num_reps: 8)
@wy = State.create(name: "Wyoming", abbreviation: 'WY', population: 568300, num_reps: 1)






